### ISSUE TITLE
kvstore: add an in-memory cache with configurable max item count 

### ISSUE THREAD

**Issue by applike-ss** [applike/gosoline#143]
We should add another cache layer into the kvstore which would be in-memory to reduce network usage whenever possible.

This is useful the most for applications that hold a small data set in their kvstore that is frequently used.

**Comment by ajscholl** [comment]
We currently have this already without the configurable max item count, do we need to keep this open?

**Comment by applike-ss** [comment]
i would like to have a max items settings, so that we don't bloat memory. Also might come in handy when creating migration apps which may want to have an in-memory cache for some things, but not all high costs.
