### ISSUE TITLE
fixture-loader: introduce fixture-loader module mvp

### ISSUE THREAD

**Issue by josketres** [applike/gosoline#166]
Introduce a new module for fixture loading.

- MVP (will iterate on it later).
- Each fixture loader has a target component/package/service.
- First implementation for target mysql.

See also some thoughts about possible features here: https://docs.google.com/document/d/13Vuil0Jxc-x_-uFrEwwbLb3NZXAuSDltBTHKPYuqDOU/edit?ts=5e4a40e3

**Comment by bogdanfinn** [comment]
@josketres added a link to the merge request in this ticket.
