### ISSUE TITLE
test-components: introduce test-component module mvp

### ISSUE THREAD

**Issue by josketres** [applike/gosoline#169]
Introduce a new package for test-components.

A test component starts a docker container providing a service (mysql, sqs, sns, etc...)
It should be used to prepare preconditions for integration tests.

- MVP (will iterate on it later).
- Each test component has a target component/package/service.
- First implementation for target mysql.

**Hint:** there is already a first iteration of this components in a branch from @ss89 

See also some thoughts about possible features here: https://docs.google.com/document/d/13Vuil0Jxc-x_-uFrEwwbLb3NZXAuSDltBTHKPYuqDOU/edit?ts=5e4a40e3

**Comment by applike-ss** [comment]
closed because #174 was merged
