### ISSUE TITLE
Message deduplication is broken

### ISSUE THREAD

**Issue by ajscholl** [applike/gosoline#220]
As a developer I am seeing one message object which is send to SQS. If I then enable content based deduplication I expect to only ever send one such object to my queue (in a certain time frame). What is happening is however a different story. Gosoline collects some attributes and stores an object in the queue with attribute and body fields. Thus, the traceId from the context can end up in my message. However, that ID is random, so I will always get a different message from SQSs perspective and content based deduplication no longer works.

To fix this, we should send a message deduplication ID to SQS together with the message instead of letting SQS handle this itself. We could also move the attributes to SQS attributes, but that does sound a lot more complicated.

**Comment by j4k4** [comment]
The purpose of the stream producer / output / input / consumer stuff is to create a generic way to exchange messages. It has also the opportunity to exchange the underlying _transport_ layer. As a drawback, you can't use any transport related features like sqs message deduplication, but this approach works very well for ~95% of our use cases and should be the same for others.

Hacking these features into the stream abstraction could be difficult and ugly. Instead, one could use the sqs _transport_ directly. If you need message deduplication from sqs, use the sqs package. One could still use the message encoder from the stream package to have fully featured message creation.

Any thoughts about this?

**Comment by ajscholl** [comment]
Hmm, sounds reasonable... In that case I would argue that configuring a queue in the config.yml to use message deduplication and then using the generic interface should throw an error explaining the problem instead of silently working wrongly. Will take a look at how I can use a specialized transport instead.

**Comment by j4k4** [comment]
Maybe we have to remove the configuration value? Doesn't make sense to have it configurable if it never works?
