### ISSUE TITLE
replace s3 integration test component with minio

### ISSUE THREAD

**Issue by applike-ss** [applike/gosoline#374]
Hey all,

i would like to replace the s3 integration test component (currently localstack) with minio (https://hub.docker.com/r/minio/minio/), because it is way smaller in image size and starts up within 1-2 seconds where localstack takes about 20-25 seconds just for the s3 service.

Any hard feelings about doing/not doing this change?

best

EDIT: dockerhub link: https://hub.docker.com/r/minio/minio/

**Comment by j4k4** [comment]
if it's compatible and faster, i'm open to it!

**Comment by applike-ss** [comment]
closed, because it got integrated in #375
