### ISSUE TITLE
Add a fixture loader for S3

### ISSUE THREAD

**Issue by applike-ss** [applike/gosoline#448]
For loading data e.g. for integration tests or for local development we added fixture loaders.

Currently we do have a fixture loader for redis/redis-kvstore/ddb/ddb-kvstore/mysql-orm/mysql-plain, but not for S3.

However that would be very handy for testing certain scenarios.

Check these for reference:
* pkg/fixtures:
  * writer_ddb.go
  * writer_ddb_kvstore.go
  * writer_mysql_orm.go
  * writer_mysql_plain.go
  * writer_redis.go
  * writer_redis_kvstore.go
  * purger_dynamodb.go
  * purger_mysql.go
  * purger_redis.go
* test:
  * fixtures_dynamodb_test.go
  * fixtures_mysql_test.go
  * fixtures_redis_test.go

The task is:
* Add a fixture loader for S3
* Add a purger for the S3 Fixture loader
* Add an integration test that validates the loader works
* Add an integration test that validates the purger works

**Comment by ss89** [comment]
closed by #452
